"""Persist an ``ExecutionPlan`` to disk in three useful formats.

A plan is the final shareable artifact:

    * ``<name>.plan.json``  — machine-readable, used by the simulator and run loop.
    * ``<name>.left.gcode`` — G-code subset for arm-left (for engineering review).
    * ``<name>.right.gcode``— G-code subset for arm-right.
    * ``<name>.turntable.csv`` — (t, angle) for the Aerotech controller.
"""
from __future__ import annotations

import csv
import json
from dataclasses import asdict
from pathlib import Path

from ..coordination.scheduler import ExecutionPlan, TimedWaypoint


def write_plan(plan: ExecutionPlan, out_stem: str | Path) -> dict[str, Path]:
    out_stem = Path(out_stem)
    out_stem.parent.mkdir(parents=True, exist_ok=True)

    json_path = out_stem.with_suffix(".plan.json")
    left_gcode = out_stem.with_suffix(".left.gcode")
    right_gcode = out_stem.with_suffix(".right.gcode")
    turntable_csv = out_stem.with_suffix(".turntable.csv")

    json_path.write_text(
        json.dumps(
            {
                "total_time_s": plan.total_time_s,
                "left_waypoints": [asdict(w) for w in plan.left_waypoints],
                "right_waypoints": [asdict(w) for w in plan.right_waypoints],
                "turntable_schedule": list(plan.turntable_schedule),
            },
            indent=2,
        )
    )
    _waypoints_to_gcode(plan.left_waypoints, left_gcode)
    _waypoints_to_gcode(plan.right_waypoints, right_gcode)

    with turntable_csv.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["t_s", "angle_deg"])
        for t, a in plan.turntable_schedule:
            w.writerow([f"{t:.6f}", f"{(a*57.2957795):.6f}"])

    return {
        "plan_json": json_path,
        "left_gcode": left_gcode,
        "right_gcode": right_gcode,
        "turntable_csv": turntable_csv,
    }


def _waypoints_to_gcode(waypoints: list[TimedWaypoint], path: Path) -> None:
    lines = ["; generated by dual_arm_printer", "G21 ; mm", "G90 ; absolute"]
    e_acc = 0.0
    for wp in waypoints:
        cmd = "G0" if wp.is_travel else "G1"
        feed = wp.feed_mm_s * 60.0
        x, y, z = wp.xyz_mm
        if wp.is_travel:
            lines.append(f"{cmd} X{x:.3f} Y{y:.3f} Z{z:.3f} F{feed:.0f}")
        else:
            e_acc += wp.extrude_mm
            lines.append(
                f"{cmd} X{x:.3f} Y{y:.3f} Z{z:.3f} E{e_acc:.4f} F{feed:.0f}"
            )
    path.write_text("\n".join(lines) + "\n")
