"""
Frame calibration: map each arm's base-frame pose into the shared world frame.

The control panel and hardware speak in **per-arm base frames** (mm / deg).
The 3D twin needs everything in one **world frame** whose origin is the disc
centre (see config/calibration.yaml and config/system.yaml).  This module is
the single place that conversion lives, so the twin and any collision / overlay
logic all agree.

Conversion (per arm), using the measured anchor ``c = turntable_centre_in_base``
and base rotation ``psi = base_yaw_deg`` about world +Z:

    world_xy = Rz(psi) . (arm_xy - c)
    world_z  = arm_z - disc_surface_z_in_base
    world_yaw = arm_yaw + psi          (roll/pitch unchanged; Rz is about Z)

The inverse (``world_to_arm``) lets the twin or planners express a world target
back in a specific arm's command frame.

Only the standard library is used (no numpy) so the unit tests run anywhere.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

import yaml

from src.safe_zones import SafeZones

Pose6 = Tuple[float, float, float, float, float, float]
XYZ = Tuple[float, float, float]

_CONFIG_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "config"
)
_DEFAULT_PATH = os.path.join(_CONFIG_DIR, "calibration.yaml")
# Captured anchors are written here and merged over the documented defaults, so
# calibration.yaml (with all its comments) is never rewritten by the capture
# helper.
_LOCAL_PATH = os.path.join(_CONFIG_DIR, "calibration_local.yaml")


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge ``override`` into a copy of ``base``."""
    out = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def capture_disc_centre(arm: str, pose: Pose6,
                        local_path: Optional[str] = _LOCAL_PATH) -> dict:
    """Record an arm's current pose as the disc-centre anchor for that arm.

    Jog the arm so its nozzle sits exactly over the disc centre, read the pose
    (e.g. ``ArmController.get_pose()``), and pass it here. The X/Y become the
    arm's ``turntable_centre_in_base_mm`` and Z becomes ``disc_surface_z_in_base_mm``.
    Written to calibration_local.yaml and merged over the defaults on next load.

    Returns the updated local-override dict.
    """
    x, y, z = pose[0], pose[1], pose[2]
    local = {}
    if local_path and os.path.exists(local_path):
        with open(local_path, "r") as f:
            local = yaml.safe_load(f) or {}
    local.setdefault("arms", {}).setdefault(arm, {})
    local["arms"][arm]["turntable_centre_in_base_mm"] = [round(x, 3), round(y, 3)]
    local["arms"][arm]["disc_surface_z_in_base_mm"] = round(z, 3)
    if local_path:
        with open(local_path, "w") as f:
            f.write("# Auto-generated by capture_disc_centre(). Safe to delete to\n")
            f.write("# revert to the documented anchors in calibration.yaml.\n")
            yaml.safe_dump(local, f, default_flow_style=False, sort_keys=False)
    return local


def normalize_deg(deg: float) -> float:
    """Wrap an angle to [0, 360) for display."""
    return deg % 360.0


def _rot2d(x: float, y: float, deg: float) -> Tuple[float, float]:
    """Rotate (x, y) by ``deg`` degrees about the origin (CCW, +Z)."""
    t = math.radians(deg)
    c, s = math.cos(t), math.sin(t)
    return (x * c - y * s, x * s + y * c)


@dataclass(frozen=True)
class ArmCalibration:
    """Per-arm anchor that ties its base frame to the world frame."""

    base_yaw_deg: float
    turntable_centre_in_base_mm: Tuple[float, float]
    disc_surface_z_in_base_mm: float

    def arm_to_world(self, pose: Pose6) -> Pose6:
        """Arm base-frame pose (mm/deg) -> world-frame pose (mm/deg)."""
        x, y, z, roll, pitch, yaw = pose
        cx, cy = self.turntable_centre_in_base_mm
        wx, wy = _rot2d(x - cx, y - cy, self.base_yaw_deg)
        wz = z - self.disc_surface_z_in_base_mm
        # No modulo: keep yaw additive so world_to_arm is an exact inverse.
        # Use normalize_deg() at display time if a 0..360 value is wanted.
        wyaw = yaw + self.base_yaw_deg
        return (wx, wy, wz, roll, pitch, wyaw)

    def world_to_arm(self, world_pose: Pose6) -> Pose6:
        """World-frame pose (mm/deg) -> this arm's base-frame command pose."""
        wx, wy, wz, roll, pitch, wyaw = world_pose
        cx, cy = self.turntable_centre_in_base_mm
        rx, ry = _rot2d(wx, wy, -self.base_yaw_deg)
        x = rx + cx
        y = ry + cy
        z = wz + self.disc_surface_z_in_base_mm
        yaw = wyaw - self.base_yaw_deg
        return (x, y, z, roll, pitch, yaw)

    def base_world_xyz(self) -> XYZ:
        """World position of this arm's base origin (arm 0,0,0)."""
        wx, wy, wz, *_ = self.arm_to_world((0.0, 0.0, 0.0, 0.0, 0.0, 0.0))
        return (wx, wy, wz)


@dataclass(frozen=True)
class Calibration:
    """Whole-cell calibration loaded from calibration.yaml."""

    arms: Dict[str, ArmCalibration]
    disc_radius_mm: float
    disc_surface_thickness_mm: float
    turntable_home_offset_deg: float
    turntable_direction: int
    safe_zones: SafeZones

    # -- construction ----------------------------------------------------

    @classmethod
    def load(cls, path: Optional[str] = None,
             local_path: Optional[str] = _LOCAL_PATH) -> "Calibration":
        """Load the documented defaults, then merge any captured local anchors.

        ``local_path=None`` skips the override (useful in tests).
        """
        with open(path or _DEFAULT_PATH, "r") as f:
            cfg = yaml.safe_load(f)
        if local_path and os.path.exists(local_path):
            with open(local_path, "r") as f:
                local = yaml.safe_load(f) or {}
            cfg = _deep_merge(cfg, local)
        return cls.from_dict(cfg)

    @classmethod
    def from_dict(cls, cfg: dict) -> "Calibration":
        arms = {
            name: ArmCalibration(
                base_yaw_deg=float(a["base_yaw_deg"]),
                turntable_centre_in_base_mm=tuple(a["turntable_centre_in_base_mm"]),
                disc_surface_z_in_base_mm=float(a["disc_surface_z_in_base_mm"]),
            )
            for name, a in cfg["arms"].items()
        }
        world = cfg.get("world", {})
        tt = cfg.get("turntable", {})
        return cls(
            arms=arms,
            disc_radius_mm=float(world.get("disc_radius_mm", 300.0)),
            disc_surface_thickness_mm=float(world.get("disc_surface_thickness_mm", 6.0)),
            turntable_home_offset_deg=float(tt.get("home_offset_deg", 0.0)),
            turntable_direction=int(tt.get("direction", 1)),
            safe_zones=SafeZones.from_dict(cfg.get("safe_zones", {})),
        )

    # -- convenience -----------------------------------------------------

    def arm_to_world(self, arm: str, pose: Pose6) -> Pose6:
        return self.arms[arm].arm_to_world(pose)

    def world_to_arm(self, arm: str, world_pose: Pose6) -> Pose6:
        return self.arms[arm].world_to_arm(world_pose)

    def base_world_xyz(self, arm: str) -> XYZ:
        return self.arms[arm].base_world_xyz()

    def turntable_world_deg(self, commanded_deg: float) -> float:
        """Commanded turntable angle -> disc orientation in the world frame."""
        return self.turntable_home_offset_deg + self.turntable_direction * commanded_deg

    def cross_check(self, pose_left: Pose6, pose_right: Pose6) -> float:
        """Validate the relative base rotation.

        Given the LEFT and RIGHT arm poses while both nozzles touch the SAME
        physical point, return the world-frame XY distance between where the two
        calibrations think that point is. A well-calibrated cell -> ~0 mm; a
        large value means base_yaw_deg (or an anchor) is off.
        """
        lx, ly, *_ = self.arm_to_world("left", pose_left)
        rx, ry, *_ = self.arm_to_world("right", pose_right)
        return math.hypot(lx - rx, ly - ry)
